=== Arhor/university/university-database/src/main/resources/sql/sql-module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.arhor.by/sql-module"
            xmlns:tns="http://www.arhor.by/sql-module"
            elementFormDefault="qualified">

    <!--  Root element declaration  -->
    <xsd:element name="module" type="tns:module"/>

    <!--  Root element structure  -->
    <xsd:complexType name="module">
        <xsd:sequence>
            <xsd:element name="dependencies" type="tns:dependencies" minOccurs="0"/>
            <xsd:element name="queries" type="tns:queries"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="dependencies">
        <xsd:sequence>
            <xsd:element name="dependency" type="tns:dependency" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="dependency">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="queries">
        <xsd:sequence>
            <xsd:element name="query" type="tns:query" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="context" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="query">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="context" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== Arhor/university/university-database/src/main/resources/sql/data/init-enrollees_has_subjects.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.arhor.by/sql-module ./../sql-module.xsd"
        xmlns="http://www.arhor.by/sql-module"
        name="init-enrollees_has_subjects">

    <dependencies>
        <dependency name="enrollees"/>
        <dependency name="subjects"/>
        <dependency name="enrollees_has_subjects"/>
        <dependency name="init-enrollees"/>
        <dependency name="init-subjects"/>
    </dependencies>

    <queries context="university">
        <util>
            <![CDATA[
            TRUNCATE TABLE enrollees_has_subjects
            ]]>
        </util>

        <insert>
            <![CDATA[
            DECLARE @subjectsRequired INT = 3

            DECLARE @totalFaculties INT = (SELECT COUNT(*) FROM faculties WITH(NOLOCK))
            DECLARE @totalEnrollees INT = (SELECT COUNT(*) FROM enrollees WITH(NOLOCK))

            DECLARE @counter INT = 0

            WHILE (@counter < @totalEnrollees)
            BEGIN
                DECLARE @enrolleeId BIGINT = (
                    SELECT e.id
                    FROM enrollees e WITH(NOLOCK)
                    ORDER BY e.id ASC
                    OFFSET @counter ROWS
                    FETCH NEXT 1 ROWS ONLY
                )

                IF ((SELECT COUNT(*) FROM enrollees_has_subjects es WHERE es.enrollee_id = @enrolleeId) < @subjectsRequired)
                BEGIN
                    PRINT N'Generating subjects for enrollee with ID = ' + CAST(@enrolleeId AS NVARCHAR(30))

                    SET TRANSACTION ISOLATION LEVEL READ COMMITTED
                    BEGIN TRANSACTION
                        DELETE FROM enrollees_has_subjects WHERE enrollee_id = @enrolleeId

                        DECLARE @facultyId BIGINT = (
                            SELECT f.id
                            FROM faculties f
                            ORDER BY f.id ASC
                            OFFSET CAST(FLOOR(@totalFaculties * RAND()) AS INT) ROWS
                            FETCH NEXT 1 ROWS ONLY
                        )

                        DECLARE @subjectsCount INT = 0

                        WHILE (@subjectsCount < @subjectsRequired)
                        BEGIN
                            DECLARE @subjectId BIGINT = (
                                SELECT fhs.subject_id
                                FROM faculties_has_subjects fhs
                                WHERE fhs.faculty_id = @facultyId
                                ORDER BY fhs.faculty_id ASC
                                OFFSET @subjectsCount ROWS
                                FETCH NEXT 1 ROWS ONLY
                            )

                            INSERT INTO enrollees_has_subjects (enrollee_id, subject_id, score)
                            VALUES
                            (
                                @enrolleeId,
                                @subjectId,
                                CEILING(100 * RAND())
                            )


                            SET @subjectsCount = @subjectsCount + 1
                        END

                    COMMIT TRANSACTION
                    PRINT N'Success' + (CHAR(13) + CHAR(10)) -- line-break CR + LF
                END

                SET @counter = @counter + 1
            END
            ]]>
        </insert>
    </queries>

</module>

=== Arhor/university/university-database/src/main/resources/sql/procedures/createNewUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.arhor.by/sql-module ./../sql-module.xsd"
        xmlns="http://www.arhor.by/sql-module"
        name="createNewUser">

    <dependencies>
        <dependency name="roles"/>
        <dependency name="langs"/>
        <dependency name="users"/>
        <dependency name="getDefaultRole"/>
        <dependency name="getDefaultLang"/>
    </dependencies>

    <queries context="university">
        <drop target="procedure">
            <![CDATA[
            IF (OBJECT_ID('createNewUser') IS NOT NULL)
            BEGIN
                DROP PROCEDURE createNewUser
            END
            ]]>
        </drop>

        <create target="procedure">
             <![CDATA[
             CREATE PROCEDURE dbo.createNewUser
                 @email         NVARCHAR(255),
                 @password      NVARCHAR(512),
                 @first_name    NVARCHAR(50),
                 @last_name     NVARCHAR(50),
                 @role_id       BIGINT,
                 @lang_id       BIGINT
             AS
             BEGIN
                 DECLARE @default_role_id BIGINT
                 DECLARE @default_lang_id BIGINT

                 EXECUTE @default_role_id = dbo.getDefaultRole;
                 EXECUTE @default_lang_id = dbo.getDefaultLang;

                 INSERT INTO users
                 (
                    email,
                    password,
                    first_name,
                    last_name,
                    role_id,
                    lang_id
                 )
                 VALUES
                 (
                     @email,
                     @password,
                     @first_name,
                     @last_name,
                     COALESCE(@role_id, @default_role_id),
                     COALESCE(@lang_id, @default_lang_id)
                 )

                 SELECT u.id
                      , u.email
                      , u.password
                      , u.first_name
                      , u.last_name
                      , u.role_id
                      , u.lang_id
                 FROM users u WITH(NOLOCK)
                 WHERE u.email = @email
             END
             ]]>
        </create>
    </queries>

</module>

=== Arhor/university/university-database/src/main/resources/sql/data/init-faculties_has_subjects.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.arhor.by/sql-module ./../sql-module.xsd"
        xmlns="http://www.arhor.by/sql-module"
        name="init-faculties_has_subjects">

    <dependencies>
        <dependency name="faculties"/>
        <dependency name="subjects"/>
        <dependency name="faculties_has_subjects"/>
        <dependency name="init-faculties"/>
        <dependency name="init-subjects"/>
    </dependencies>

    <queries context="university">
        <insert>
            <![CDATA[
            DECLARE @facultyId BIGINT
            DECLARE @subjectId BIGINT

            --------------------------- Биологический факультет ---------------------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Биологический факультет'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Биология')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Химия')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Русский язык'))

            ---------------------------- Исторический факультет ---------------------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Исторический факультет'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Белорусский язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Иностранный язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'История'))

            -------------------------- Химический факультет -------------------------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Химический факультет'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Химия')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Русский язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Физика'))

            ---------------- Факультет прикладной математики и информатики ----------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Факультет прикладной математики и информатики'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Математика')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Иностранный язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Физика'))

            ------------- Факультет радиофизики и компьютерных технологий -----------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Факультет радиофизики и компьютерных технологий'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Физика')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Математика')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Химия'))

            ------------------------- Экономический факультет -----------------------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Экономический факультет'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Иностранный язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'История')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Математика'))

            -------------------------- Юридический факультет ------------------------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Юридический факультет'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Белорусский язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Иностранный язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'История'))

            ---------------------------- Военный факультет --------------------------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Военный факультет'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Химия')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Белорусский язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'История'))

            ------------------------ Филологический факультет -----------------------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Филологический факультет'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Русский язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Белорусский язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Иностранный язык'))

            ------------ Республиканский институт китаеведения имени Конфуция -------------
            SELECT @facultyId = id FROM faculties WITH(NOLOCK) WHERE default_title = N'Республиканский институт китаеведения имени Конфуция'

            INSERT INTO faculties_has_subjects (faculty_id, subject_id)
            VALUES
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Иностранный язык')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'История')),
            (@facultyId, (SELECT id FROM subjects WITH(NOLOCK) WHERE default_title = N'Биология'))
            ]]>
        </insert>
    </queries>

</module>

=== Arhor/university/university-database/src/main/resources/sql/data/init-faculties_has_enrollees.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.arhor.by/sql-module ./../sql-module.xsd"
        xmlns="http://www.arhor.by/sql-module"
        name="init-faculties_has_enrollees">

    <dependencies>
        <dependency name="enrollees"/>
        <dependency name="faculties"/>
        <dependency name="enrollees_has_subjects"/>
        <dependency name="faculties_has_enrollees"/>
        <dependency name="faculties_has_subjects"/>
        <dependency name="init-enrollees"/>
        <dependency name="init-faculties"/>
        <dependency name="init-enrollees_has_subjects"/>
        <dependency name="init-faculties_has_subjects"/>
    </dependencies>

    <queries context="university">
        <util>
            <![CDATA[
            TRUNCATE TABLE faculties_has_enrollees
            ]]>
        </util>

        <insert>
            <![CDATA[
            DECLARE @totalEnrollees INT = (SELECT COUNT(*) FROM enrollees WITH(NOLOCK))
            DECLARE @subjectsMin    INT = 3
            DECLARE @counter        INT = 0

            WHILE (@counter < @totalEnrollees)
            BEGIN
                DECLARE @enrolleeId BIGINT = (
                    SELECT e.id
                    FROM enrollees e WITH(NOLOCK)
                    ORDER BY e.id ASC
                    OFFSET @counter ROWS
                    FETCH NEXT 1 ROWS ONLY
                )

                IF NOT EXISTS (SELECT * FROM faculties_has_enrollees WITH(NOLOCK) WHERE enrollee_id = @enrolleeId)
                BEGIN
                    PRINT N'Looking for appropriate faculty for enrollee with ID = ' + CAST(@enrolleeId AS NVARCHAR(30))

                    DECLARE @availableFaculties TABLE(id BIGINT)

                    INSERT INTO @availableFaculties (id)
                    SELECT f.id
                    FROM faculties f WITH(NOLOCK)
                    JOIN faculties_has_subjects fs WITH(NOLOCK) ON fs.faculty_id = f.id
                    WHERE fs.subject_id IN (
                        SELECT es.subject_id
                        FROM enrollees_has_subjects es WITH(NOLOCK)
                        WHERE es.enrollee_id = @enrolleeId
                    )
                    GROUP BY f.id
                    HAVING COUNT(f.id) >= @subjectsMin

                    DECLARE @facultyId BIGINT = (
                        SELECT id FROM @availableFaculties
                        ORDER BY id
                        OFFSET CAST(FLOOR((SELECT COUNT(*) FROM @availableFaculties) * RAND()) AS INT) ROWS
                        FETCH NEXT 1 ROWS ONLY
                    )

                    IF (@facultyId IS NOT NULL)
                    BEGIN
                        INSERT INTO faculties_has_enrollees (faculty_id, enrollee_id, filing_date)
                        VALUES (@facultyId, @enrolleeId, GETDATE())
                    END
                END
                SET @counter = @counter + 1
            END
            ]]>
        </insert>
    </queries>

</module>
